phone:
  number:
    onnetPrefix: '5([0-9]{7})'
    offnetPrefix: '(2[0-9]{7})|(9[0-9]{7})'
    countryPhonePrefix: 216
    defaultCountryCode: TN

server:
  port: 0
#allow more than one instance
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
